# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gtfsort_wrappers", use_symbols = TRUE, package_name = "gtfsort")

#' @usage NULL
#' @useDynLib gtfsort, .registration = TRUE
NULL

#' Sort a GTF/GFF/GFF3 file.
#'
#' @param input The input file path.
#' @param output The output file path.
#' @param threads The number of threads to use.
#' @return a list with the input and output file paths, the number of threads used, whether the input and output were memory-mapped, the time taken to parse, index, and write the output, and the memory used before and after the operation.
#'
#' @examples
#' sort_annotations("tests/data/chr1.gtf", "tests/data/chr1.sorted.gtf", 1)
#'
#' @export
sort_annotations <- function(input, output, threads) .Call(wrap__sort_annotations, input, output, threads)

#' Sort a string with GTF/GFF/GFF3 annotations.
#'
#' @param mode The mode to parse the annotations. Either "gtf" or "gff" or "gff3".
#' @param input The string with the GTF/GFF/GFF3 annotations.
#' @param output A function that will be called with each chunk of the sorted string. Return NULL to continue, or a string to stop.
#' @param threads The number of threads to use.
#' @return a list with the input and output strings, the number of threads used, whether the input and output were memory-mapped, the time taken to parse, index, and write the output, and the memory used before and after the operation.
#'
#' @examples
#' sort_annotations_str("gtf", "chr1\t.\texon\t11869\t12227\t.\t+\t.\tgene_id \"ENSG00000223972.5\"; transcript_id \"ENST00000456328.2\"; exon_number \"1\";\nchr1\t.\texon\t12613\t12721\t.\t+\t.\tgene_id \"ENSG00000223972.5\"; transcript_id \"ENST00000456328.2\"; exon_number \"2\";", function(str) { cat(str); return(NULL); }, 1)
#'
#' @export
sort_annotations_str <- function(mode, input, output, threads) .Call(wrap__sort_annotations_str, mode, input, output, threads)


# nolint end
