name: Benchmark

on:
  workflow_run:
    workflows: ["Cargo Check"]
    types:
      - completed

jobs:
  benchmark:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts
    
      - name: Install Hyperfine
        run: cargo install hyperfine --force --locked
      
      - name: Run Benchmark
        env:
          GITHUB_REPO_OWNER: ${{ github.event.repository.owner.login }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./benchmark.sh
      
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
            name: benchmark-results
            path: |
              tests/benchmark_*.csv
              tests/benchmark_*.md
              tests/benchmark-output.txt
