name: Benchmark

on:
  workflow_run:
    workflows: ["Cargo Check"]
    types:
      - completed

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
    
      - name: Install Hyperfine
        run: cargo install hyperfine --force --locked
    
      - name: Set Upstream
        run: git remote add upstream https://github.com/alejandrogzi/gtfsort.git
    
      - name: Fetch Upstream
        run: git fetch upstream

      - name: Build Benchmark
        run: cargo build --release --bin gtfsort-benchmark --features "mmap benchmark"
      
      - name: Run Benchmark
        env:
          GITHUB_REPO_OWNER: ${{ github.event.repository.owner.login }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: target/release/gtfsort-benchmark -r upstream/master -- --show-output
      
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
            name: benchmark-results-${{ matrix.os }}
            path: |
              tests/benchmark_*.csv
              tests/benchmark_*.md
              tests/benchmark-output.txt
